### ISSUE TITLE
`tglc_lc` fails in case of multiple sectors

### ISSUE THREAD

**Issue by astrobatty** [TeHanHunter/TESS_Gaia_Light_Curve#2]
Hi,

I tried the code as it is written in the tutorial notebook, and it only works if I query the first sector alone. Whenever I specify a sector number, no matter if `first_sector_only` is set to `True` or `False`, `tglc_lc` fails with the following exception:

```
Traceback (most recent call last):
  File "/Users/batty/Downloads/TESS-Gaia_lc/tessgaia.py", line 23, in <module>
    tglc_lc(target=target,
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/site-packages/tglc/quick_lc.py", line 35, in tglc_lc
    source.select_sector(sector=source.sector_table['sector'][j])
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/site-packages/tglc/ffi_cut.py", line 106, in select_sector
    index = self.sector_list.index(sector)
ValueError: 2 is not in list
```

The `ValueError` depends on the available sectors, and in this case the second sector is `2`.
It seems like the code tries to reach the other sectors too, which were filtered out at some point according to my query.

The current target is RU Dor, which is queried as follows:

```
target = 'RU Dor'     # Target ID ('TOI 519') or coordinates ('ra dec')
local_directory = f'{target}/'    # directory to save all files
os.makedirs(local_directory, exist_ok=True)
tglc_lc(target=target,
        local_directory=local_directory,
        size=50, # FFI cutsize. Recommand 50 or larger for best performance. Cannot exceed 99.
        save_aper=False, # whether to save 5*5 timeseries of the decontaminated images in fits file primary HDU
        limit_mag=15, # the TESS magnitude limit of stars to output
        get_all_lc=False, # whether to return all lcs in the region. If False, return the nearest star to the target coordinate
        first_sector_only=False, # whether to return only lcs from the sector this target was first observed.
                                # If False, return all sectors of the target, but too many sectors could be slow.
        sector=1 # If first_sector_only=True, sector must be True
                    # If first_sector_only=False, specify a sector number to return
       )
```

**Comment by TeHanHunter** [comment]
Hi,

Thank you for your question! There is indeed a bug in the line of code. I fixed it and published the newer release (both pypi and git). I also updated the tutorial. Let me know if there are still more problems.
