### ISSUE TITLE
tglc returns KeyError

### ISSUE THREAD

**Issue by astrobatty** [TeHanHunter/TESS_Gaia_Light_Curve#3]
Hi,

When I try to run `tglc` as it is written in the examples:

```import os
import numpy as np
import matplotlib.pyplot as plt
from tglc.quick_lc import tglc_lc

target = 'TOI 519'     # Target ID ('TOI 519') or coordinates ('ra dec')
local_directory = f'{target}/'    # directory to save all files
os.makedirs(local_directory, exist_ok=True)
tglc_lc(target=target,
        local_directory=local_directory,
        size=50, # FFI cutsize. Recommand at least 50 or larger for better performance. Cannot exceed 99.
                 # Downloading FFI might take longer (or even cause timeouterror) for larger sizes.
        save_aper=False, # whether to save 5*5 pixels timeseries of the decontaminated images in fits file primary HDU
        limit_mag=15, # the TESS magnitude lower limit of stars to output
        get_all_lc=False, # whether to return all lcs in the region. If False, return the nearest star to the target coordinate
        first_sector_only=True, # whether to return only lcs from the sector this target was first observed.
                                # If False, return all sectors of the target, but too many sectors could be slow to download.
        sector=None, # If first_sector_only=True, sector will be ignored.
                     # If first_sector_only=False and sector = None, return all observed sectors
                     # If first_sector_only=False and sector = 1, return only sector 1.
                     # (Make sure only put observed sectors. All available sectors are printed in the sector table.)
        prior=None)  # If None, does not allow all field stars to float. SUGGESTED for first use.
                     # If float (usually <1), allow field stars to float with a Gaussian prior with the mean
                     # at the Gaia predicted value the width of the prior value multiplied on the Gaia predicted value.)
```

I got the following error which always returns regardless of the target.

```
Target Gaia: Gaia DR2 5707485527450614656
INFO: Query finished. [astroquery.utils.tap.core]
Found 6688 Gaia DR3 objects.
Found 974 TIC objects.
INFO: Query finished. [astroquery.utils.tap.core]
  sectorName   sector camera ccd
-------------- ------ ------ ---
tess-s0007-2-3      7      2   3
tess-s0008-2-4      8      2   4
tess-s0034-2-3     34      2   3
Traceback (most recent call last):
  File "/Users/batty/Downloads/ULA/tessgaia_test.py", line 9, in <module>
    tglc_lc(target=target,
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/site-packages/tglc/quick_lc.py", line 30, in tglc_lc
    source = ffi_cut(target=target, size=size, local_directory=local_directory, sector=sector)  # sector
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/site-packages/tglc/ffi_cut.py", line 264, in ffi_cut
    source = Source_cut(target, size=size, sector=sector)
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/site-packages/tglc/ffi_cut.py", line 91, in __init__
    self.select_sector(sector=sector)
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/site-packages/tglc/ffi_cut.py", line 136, in select_sector
    gaia_targets = self.catalogdata[
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/site-packages/astropy/table/table.py", line 2079, in __getitem__
    [self[x] for x in item], copy_indices=self._copy_indices
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/site-packages/astropy/table/table.py", line 2079, in <listcomp>
    [self[x] for x in item], copy_indices=self._copy_indices
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/site-packages/astropy/table/table.py", line 2070, in __getitem__
    return self.columns[item]
  File "/Users/batty/opt/miniconda3/envs/tessgaia/lib/python3.9/site-packages/astropy/table/table.py", line 263, in __getitem__
    return OrderedDict.__getitem__(self, item)
KeyError: 'designation'
```

**Comment by TeHanHunter** [comment]
Hi, thank you for spotting this. It seems that the astroquery.gaia package we use has updated its keys. 'designation' is replaced as 'DESIGNATION'. I have updated the package to 0.5.3. Let me know if the updated release works!

**Comment by astrobatty** [comment]
It works! Thanks.
