### ISSUE TITLE
Connection timed out error while running tutorial script.

### ISSUE THREAD

**Issue by Alakay2** [TeHanHunter/TESS_Gaia_Light_Curve#5]
Hi,
I am running the tutorial script and getting following error:

0.6.1
**Status messages could not be retrieved**
Target: TOI 519
  sectorName   sector camera ccd
-------------- ------ ------ ---
tess-s0007-2-3      7      2   3
tess-s0008-2-4      8      2   4
tess-s0034-2-3     34      2   3
tess-s0061-2-3     61      2   3
Since the provided target is not TIC ID, the resulted light curve with get_all_lc=False can not be guaranteed to be the target's light curve. Please check the TIC ID of the output file before using the light curve or try use TIC ID as the target in the format of 'TIC 12345678'.
Only processing the first sector the target is observed in: Sector 7.
Downloading Data from MAST and Gaia ...
Target Gaia: Gaia DR2 5707485527450614656
Traceback (most recent call last):
  File "/home/test/TGLC_lc_generate.py", line 21, in <module>
    tglc_lc(target=target, 
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/tglc/quick_lc.py", line 80, in tglc_lc
    source = ffi_cut(target=target, size=size, local_directory=local_directory, sector=sector,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/tglc/ffi_cut.py", line 281, in ffi_cut
    source = Source_cut(target, size=size, sector=sector, limit_mag=limit_mag, transient=transient)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/tglc/ffi_cut.py", line 67, in __init__
    catalogdata = Gaia.cone_search_async(coordinate=coord, radius=radius, columns=['DESIGNATION', 'phot_g_mean_mag', 'phot_bp_mean_mag', 'phot_rp_mean_mag', 'ra', 'dec', 'pmra', 'pmdec']).get_results()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/astroquery/gaia/core.py", line 790, in cone_search_async
    return self.__cone_search(coordinate,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/astroquery/gaia/core.py", line 684, in __cone_search
    return self.launch_job_async(query=query,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/astroquery/gaia/core.py", line 1021, in launch_job_async
    return TapPlus.launch_job_async(self, query=query,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/astroquery/utils/tap/core.py", line 429, in launch_job_async
    response = self.__launchJob(query,
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/astroquery/utils/tap/core.py", line 649, in __launchJob
    response = self.__connHandler.execute_tappost(subcontext=context,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/astroquery/utils/tap/conn/tapconn.py", line 269, in execute_tappost
    return self.__execute_post(context, data, content_type, verbose=verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/site-packages/astroquery/utils/tap/conn/tapconn.py", line 422, in __execute_post
    conn.request("POST", context, data, self.__postHeaders)
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1343, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1389, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1338, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1097, in _send_output
    self.send(msg)
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1041, in send
    self.connect()
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1477, in connect
    super().connect()
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/http/client.py", line 1007, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/home/test/anaconda3/envs/eureka/lib/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
**TimeoutError: [Errno 110] Connection timed out**

 I am using institute proxy setting but also tried with other network. I am giving proxy, port, username and password information in the beginning using **os.environ['http_proxy'] = proxy**. The issue may not be exactly related to TGLC, do you have any solution for this? Thanks in advance.

**Comment by TeHanHunter** [comment]
Hi, which version of astroquery are you using?

**Comment by Alakay2** [comment]
> Hi, which version of astroquery are you using?

Hi, astroquery version is  0.4.7. I am getting same kind of error while using eleanor as well [https://github.com/afeinstein20/eleanor/issues/273](url).

**Comment by Alakay2** [comment]
> Hmm, I know both tglc and eleanor uses tesscut, but it seems the error occurred when running astropy.Gaia. I'm not sure why. I'll try to replicate your error. Let me know if there's any updates.

I think you're right, it's occurring from astroquery.Gaia. I tried some simple example from astroquery and got same error. Even after running
>>> **from astroquery.gaia import Gaia** I get
**Status messages could not be retrieved**

and 
**r = Gaia.query_object_async(coordinate=coord, width=width, height=height)**
rerturn the same
**TimeoutError: [Errno 110] Connection timed out**

**Comment by TeHanHunter** [comment]
Has the problem been fixed? Are you still getting the same error?

**Comment by Alakay2** [comment]
> Has the problem been fixed? Are you still getting the same error?
Still getting the same error. For TGLC, eleanor and using astroquery with gaia, getting same error.

**Comment by TeHanHunter** [comment]
In that case, it's more likely a problem of the astroquery.Gaia package on your end. I did not get this error when I last tried. I recommend a fresh install in a new virtual environment. Let me know how does that go.
